resources:
- infrastructure/metrics-server-components.yaml

- infrastructure/resource-limit-all.yaml
- infrastructure/resource-limit-container.yaml

- infrastructure/dbdata.yaml
- infrastructure/redis.yaml
- infrastructure/sqlserver.yaml

- gateway-deployment.yaml
- identity-server-deploy.yaml
- identity-service-deployment.yaml
- movie-service-deployment.yaml
- payment-service-deployment.yaml
- review-service-deployment.yaml
- test-service-deployment.yaml

- gateway.yaml
- identity-server.yaml
- identity-service.yaml
- movie-service.yaml
- payment-service.yaml
- review-service.yaml
- test-service.yaml

- gateway-autoscaler.yaml
- test-service-autoscaler.yaml

- gateway-expose.yaml