version: '3.8'

services:
  app-angular:
    image: ${DOCKER_REGISTRY-}app-angular:${TAG:-latest}
    build:
      context: ../..
      dockerfile: applications/Microservice.App.Angular/docker/Dockerfile
    depends_on:
      gateway:
        condition: service_started

  app-react:
    image: ${DOCKER_REGISTRY-}app-react:${TAG:-latest}
    build:
      context: ../..
      dockerfile: applications/Microservice.App.React/docker/Dockerfile
    depends_on:
      gateway:
        condition: service_started