version: '3.4'

services:
  sqlserver:
    image: "mcr.microsoft.com/mssql/server"
    volumes:
      - dbdata:/var/opt/sqlserver  

  redis:
    image: "redis"

  rabbitmq:
    image: "rabbitmq:3-management-alpine"
    
volumes:
  dbdata: