version: '3.4'

services:
  gateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - GlobalConfiguration__BaseUrl=http://gateway
      - Routes__0__DownstreamHostAndPorts__0__Host=identity-service
      - Routes__0__DownstreamHostAndPorts__0__Port=80
      - Routes__1__DownstreamHostAndPorts__0__Host=movie-service
      - Routes__1__DownstreamHostAndPorts__0__Port=80
      - Routes__2__DownstreamHostAndPorts__0__Host=payment-service
      - Routes__2__DownstreamHostAndPorts__0__Port=80
      - Routes__3__DownstreamHostAndPorts__0__Host=review-service
      - Routes__3__DownstreamHostAndPorts__0__Port=80
      - Routes__4__DownstreamHostAndPorts__0__Host=test-service
      - Routes__4__DownstreamHostAndPorts__0__Port=80
    ports:
      - 5000:80
      
  identity-service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 5001:80
      
  movie-service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 5002:80
      
  payment-service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 5003:80
      
  review-service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 5004:80
      
  test-service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 5005:80
