version: '3.4'

services:
  gateway:
    image: gateway:${TAG:-latest}
    build:
      context: ../
      dockerfile: gateways/Microservice.Gateway.Web/Dockerfile
    depends_on:
      - identity-service
      - movie-service
      - payment-service
      - review-service
      
  identity-service:
    image: identity-service:${TAG:-latest}
    build:
      context: ../
      dockerfile: microservices/identity/Microservice.IdentityService.Web/Dockerfile
      
  movie-service:
    image: movie-service:${TAG:-latest}
    build:
      context: ../
      dockerfile: microservices/movie/Microservice.MovieService.Web/Dockerfile
      
  payment-service:
    image: payment-service:${TAG:-latest}
    build:
      context: ../
      dockerfile: microservices/payment/Microservice.PaymentService.Web/Dockerfile
      
  review-service:
    image: review-service:${TAG:-latest}
    build:
      context: ../
      dockerfile: microservices/review/Microservice.ReviewService.Web/Dockerfile