version: '3.4'

services:
  microservice-gateway-web:
    image: microservice-gateway-web:${TAG:-latest}
    build:
      context: .
      dockerfile: ../gateways/Microservice.Gateway.Web/Dockerfile
    depends_on:
      - microservice-identityservice-web
      - microservice-movieservice-web
      - microservice-paymentservice-web
      - microservice-reviewservice-web

  microservice-identityservice-web:
    image: microservice-identityservice-web:${TAG:-latest}
    build:
      context: .
      dockerfile: ../microservices/identity/Microservice.IdentityService.Web/Dockerfile


  microservice-movieservice-web:
    image: microservice-movieservice-web:${TAG:-latest}
    build:
      context: .
      dockerfile: ../microservices/movie/Microservice.MovieService.Web/Dockerfile


  microservice-paymentservice-web:
    image: microservice-paymentservice-web:${TAG:-latest}
    build:
      context: .
      dockerfile: ../microservices/payment/Microservice.PaymentService.Web/Dockerfile


  microservice-reviewservice-web:
    image: microservice-reviewservice-web:${TAG:-latest}
    build:
      context: .
      dockerfile: ../microservices/review/Microservice.ReviewService.Web/Dockerfile

