apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: gateway-autoscaler
spec:
  minReplicas: 1
  maxReplicas: 10
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: gateway
  targetCPUUtilizationPercentage: 50