kind: Deployment
apiVersion: apps/v1
metadata:
  name: gateway
spec:
  selector:
    matchLabels:
      app: gateway
  replicas: 1
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: "gateway"
          imagePullPolicy: IfNotPresent
          env:
          - name: ASPNETCORE_ENVIRONMENT
            value: Production
          - name: ASPNETCORE_URLS
            value: http://0.0.0.0:80
          - name: GlobalConfiguration__BaseUrl
            value: http://gateway
          - name: Routes__0__DownstreamHostAndPorts__0__Host
            value: identity-service
          - name: Routes__0__DownstreamHostAndPorts__0__Port
            value: "80"
          - name: Routes__1__DownstreamHostAndPorts__0__Host
            value: movie-service
          - name: Routes__1__DownstreamHostAndPorts__0__Port
            value: "80"
          - name: Routes__2__DownstreamHostAndPorts__0__Host
            value: payment-service
          - name: Routes__2__DownstreamHostAndPorts__0__Port
            value: "80"
          - name: Routes__3__DownstreamHostAndPorts__0__Host
            value: review-service
          - name: Routes__3__DownstreamHostAndPorts__0__Port
            value: "80"
          - name: Routes__4__DownstreamHostAndPorts__0__Host
            value: test-service
          - name: Routes__4__DownstreamHostAndPorts__0__Port
            value: "80"
          ports:
            - name: http
              containerPort: 80
          resources:
            limits:
              cpu: 2