apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: test-service-autoscaler
spec:
  minReplicas: 1
  maxReplicas: 10
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: test-service
  targetCPUUtilizationPercentage: 50