apiVersion: v1
kind: LimitRange
metadata:
  name: resource-limit-container
spec:
  limits:
  - default:
      cpu: 100m
      memory: 128Mi
    defaultRequest:
      cpu: 50m
      memory: 64Mi
    max:
      cpu: 2
      memory: 2Gi
    min:
      cpu: 50m
      memory: 16Mi
    type: Container