version: '3.8'

services:
  api-auth-service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ConnectionStrings__IdentityServiceDbContext=Server=sqlserver,1433;Database=Microservice.IdentityService;User Id=sa;Password=yourStrong(!)Password;TrustServerCertificate=True;
      - IdentityServer__Clients__0__RedirectUris__0=https://localhost:9200/oauth2-redirect.html
      - IdentityServer__Clients__0__RedirectUris__1=https://localhost:9201/oauth2-redirect.html
      - IdentityServer__Clients__0__RedirectUris__2=https://localhost:9202/oauth2-redirect.html
      - IdentityServer__Clients__0__RedirectUris__3=https://localhost:9203/oauth2-redirect.html
      - IdentityServer__Clients__0__RedirectUris__4=https://localhost:9204/oauth2-redirect.html
      - IdentityServer__Clients__0__RedirectUris__5=https://localhost:9205/oauth2-redirect.html
      - IdentityServer__Clients__0__AllowedCorsOrigins__0=https://localhost:9200
      - IdentityServer__Clients__0__AllowedCorsOrigins__1=https://localhost:9201
      - IdentityServer__Clients__0__AllowedCorsOrigins__2=https://localhost:9202
      - IdentityServer__Clients__0__AllowedCorsOrigins__3=https://localhost:9203
      - IdentityServer__Clients__0__AllowedCorsOrigins__4=https://localhost:9204
      - IdentityServer__Clients__0__AllowedCorsOrigins__5=https://localhost:9205
    ports:
      - 9100:443

  api-gateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443
      - GlobalConfiguration__BaseUrl=http://gateway
      - Authentication__JwtBearer__Authority=http://identity-server
      - Authentication__JwtBearer__ValidIssuer=https://localhost:9100
      - Authentication__JwtBearer__RequireHttpsMetadata=false
      - Swagger__Security__Flow__AuthorityUrl=https://localhost:9100
      - Routes__0__DownstreamScheme=http
      - Routes__0__DownstreamHostAndPorts__0__Host=api-identity-service
      - Routes__0__DownstreamHostAndPorts__0__Port=80
      - Routes__1__DownstreamScheme=http
      - Routes__1__DownstreamHostAndPorts__0__Host=api-movie-service
      - Routes__1__DownstreamHostAndPorts__0__Port=80
      - Routes__2__DownstreamScheme=http
      - Routes__2__DownstreamHostAndPorts__0__Host=api-payment-service
      - Routes__2__DownstreamHostAndPorts__0__Port=80
      - Routes__3__DownstreamScheme=http
      - Routes__3__DownstreamHostAndPorts__0__Host=api-review-service
      - Routes__3__DownstreamHostAndPorts__0__Port=80
      - Routes__4__DownstreamScheme=http
      - Routes__4__DownstreamHostAndPorts__0__Host=api-test-service
      - Routes__4__DownstreamHostAndPorts__0__Port=80
    ports:
      - 9200:443

  api-identity-service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - Authentication__JwtBearer__Authority=http://identity-server
      - Authentication__JwtBearer__ValidIssuer=https://localhost:9100
      - Authentication__JwtBearer__RequireHttpsMetadata=false
      - ConnectionStrings__IdentityServiceDbContext=Server=sqlserver,1433;Database=Microservice.IdentityService;User Id=sa;Password=yourStrong(!)Password;TrustServerCertificate=True;
      - Swagger__Security__Flow__AuthorityUrl=https://localhost:9100
    ports:
      - 9201:443

  migrator-identity-service:
    environment:
      - ConnectionStrings__IdentityServiceDbContext=Server=sqlserver,1433;Database=Microservice.IdentityService;User Id=sa;Password=yourStrong(!)Password;TrustServerCertificate=True;
      
  api-movie-service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - Authentication__JwtBearer__Authority=http://identity-server
      - Authentication__JwtBearer__ValidIssuer=https://localhost:9100
      - Authentication__JwtBearer__RequireHttpsMetadata=false
      - ConnectionStrings__MovieServiceDbContext=Server=sqlserver,1433;Database=Microservice.MovieService;User Id=sa;Password=yourStrong(!)Password;TrustServerCertificate=True;
      - Swagger__Security__Flow__AuthorityUrl=https://localhost:9100
    ports:
      - 9202:443

  migrator-movie-service:
    environment:
      - ConnectionStrings__MovieServiceDbContext=Server=sqlserver,1433;Database=Microservice.MovieService;User Id=sa;Password=yourStrong(!)Password;TrustServerCertificate=True;
      
  api-payment-service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - Authentication__JwtBearer__Authority=http://identity-server
      - Authentication__JwtBearer__ValidIssuer=https://localhost:9100
      - Authentication__JwtBearer__RequireHttpsMetadata=false
      - ConnectionStrings__PaymentServiceDbContext=Server=sqlserver,1433;Database=Microservice.PaymentService;User Id=sa;Password=yourStrong(!)Password;TrustServerCertificate=True;
      - Swagger__Security__Flow__AuthorityUrl=https://localhost:9100
    ports:
      - 9203:443

  migrator-payment-service:
    environment:
      - ConnectionStrings__PaymentServiceDbContext=Server=sqlserver,1433;Database=Microservice.PaymentService;User Id=sa;Password=yourStrong(!)Password;TrustServerCertificate=True;
      
  api-review-service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - Authentication__JwtBearer__Authority=http://identity-server
      - Authentication__JwtBearer__ValidIssuer=https://localhost:9100
      - Authentication__JwtBearer__RequireHttpsMetadata=false
      - ConnectionStrings__ReviewServiceDbContext=Server=sqlserver,1433;Database=Microservice.ReviewService;User Id=sa;Password=yourStrong(!)Password;TrustServerCertificate=True;
      - Swagger__Security__Flow__AuthorityUrl=https://localhost:9100
    ports:
      - 9204:443

  migrator-review-service:
    environment:
      - ConnectionStrings__ReviewServiceDbContext=Server=sqlserver,1433;Database=Microservice.ReviewService;User Id=sa;Password=yourStrong(!)Password;TrustServerCertificate=True;
      
  api-test-service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - Authentication__JwtBearer__Authority=http://identity-server
      - Authentication__JwtBearer__ValidIssuer=https://localhost:9100
      - Authentication__JwtBearer__RequireHttpsMetadata=false
      - ConnectionStrings__TestServiceDbContext=Server=sqlserver,1433;Database=Microservice.TestService;User Id=sa;Password=yourStrong(!)Password;TrustServerCertificate=True;
      - RabbitMq__Host=rabbitmq
      - Swagger__Security__Flow__AuthorityUrl=https://localhost:9100
    ports:
      - 9205:443

  migrator-test-service:
    environment:
      - ConnectionStrings__TestServiceDbContext=Server=sqlserver,1433;Database=Microservice.TestService;User Id=sa;Password=yourStrong(!)Password;TrustServerCertificate=True;