version: '3.8'

services:
  api-auth-service:
    image: ${DOCKER_REGISTRY}${DOCKER_REGISTRY:+/}api-auth-service:${TAG:-latest}
    build:
      context: ../..
      dockerfile: applications/Microservice.Api.AuthService/Dockerfile
  
  api-gateway-service:
    image: ${DOCKER_REGISTRY}${DOCKER_REGISTRY:+/}api-gateway-service:${TAG:-latest}
    build:
      context: ../..
      dockerfile: applications/Microservice.Api.GatewayService/Dockerfile

  api-identity-service:
    image: ${DOCKER_REGISTRY}${DOCKER_REGISTRY:+/}api-identity-service:${TAG:-latest}
    build:
      context: ../..
      dockerfile: microservices/identity/Microservice.Api.IdentityService/Dockerfile

  api-identity-service-migrator:
    image:  ${DOCKER_REGISTRY}${DOCKER_REGISTRY:+/}api-identity-service-migrator:${TAG:-latest}
    build:
      context: ../..
      dockerfile: microservices/identity/Microservice.Api.IdentityService.Migrator/Dockerfile

  api-movie-service:
    image: ${DOCKER_REGISTRY}${DOCKER_REGISTRY:+/}api-movie-service:${TAG:-latest}
    build:
      context: ../..
      dockerfile: microservices/movie/Microservice.Api.MovieService/Dockerfile

  api-movie-service-migrator:
    image:  ${DOCKER_REGISTRY}${DOCKER_REGISTRY:+/}api-movie-service-migrator:${TAG:-latest}
    build:
      context: ../..
      dockerfile: microservices/movie/Microservice.Api.MovieService.Migrator/Dockerfile

  api-payment-service:
    image: ${DOCKER_REGISTRY}${DOCKER_REGISTRY:+/}api-payment-service:${TAG:-latest}
    build:
      context: ../..
      dockerfile: microservices/payment/Microservice.Api.PaymentService/Dockerfile

  api-payment-service-migrator:
    image:  ${DOCKER_REGISTRY}${DOCKER_REGISTRY:+/}api-payment-service-migrator:${TAG:-latest}
    build:
      context: ../..
      dockerfile: microservices/payment/Microservice.Api.PaymentService.Migrator/Dockerfile

  api-review-service:
    image: ${DOCKER_REGISTRY}${DOCKER_REGISTRY:+/}api-review-service:${TAG:-latest}
    build:
      context: ../..
      dockerfile: microservices/review/Microservice.Api.ReviewService/Dockerfile

  api-review-service-migrator:
    image:  ${DOCKER_REGISTRY}${DOCKER_REGISTRY:+/}api-review-service-migrator:${TAG:-latest}
    build:
      context: ../..
      dockerfile: microservices/review/Microservice.Api.ReviewService.Migrator/Dockerfile

  api-test-service:
    image: ${DOCKER_REGISTRY}${DOCKER_REGISTRY:+/}api-test-service:${TAG:-latest}
    build:
      context: ../..
      dockerfile: microservices/test/Microservice.Api.TestService/Dockerfile

  api-test-service-migrator:
    image:  ${DOCKER_REGISTRY}${DOCKER_REGISTRY:+/}api-test-service-migrator:${TAG:-latest}
    build:
      context: ../..
      dockerfile: microservices/test/Microservice.Api.TestService.Migrator/Dockerfile
