version: '3.8'

services:
  api-auth-service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ConnectionStrings__IdentityServiceDbContext=Server=sqlserver,1433;Database=Microservice.DB.IdentityService;User Id=sa;Password=yourStrong(!)Password;TrustServerCertificate=True;
      - IdentityServer__Clients__0__RedirectUris__0=http://localhost:9001/signin
      - IdentityServer__Clients__0__RedirectUris__1=https://localhost:9200/oauth2-redirect.html
      - IdentityServer__Clients__0__RedirectUris__2=https://localhost:9200/api/oauth2-redirect.html
      - IdentityServer__Clients__0__RedirectUris__3=https://localhost:9201/oauth2-redirect.html
      - IdentityServer__Clients__0__RedirectUris__4=https://localhost:9202/oauth2-redirect.html
      - IdentityServer__Clients__0__RedirectUris__5=https://localhost:9203/oauth2-redirect.html
      - IdentityServer__Clients__0__RedirectUris__6=https://localhost:9204/oauth2-redirect.html
      - IdentityServer__Clients__0__RedirectUris__7=https://localhost:9205/oauth2-redirect.html
      - IdentityServer__Clients__0__AllowedCorsOrigins__0=http://localhost:9001
      - IdentityServer__Clients__0__AllowedCorsOrigins__1=https://localhost:9200
      - IdentityServer__Clients__0__AllowedCorsOrigins__2=https://localhost:9201
      - IdentityServer__Clients__0__AllowedCorsOrigins__3=https://localhost:9202
      - IdentityServer__Clients__0__AllowedCorsOrigins__4=https://localhost:9203
      - IdentityServer__Clients__0__AllowedCorsOrigins__5=https://localhost:9204
      - IdentityServer__Clients__0__AllowedCorsOrigins__6=https://localhost:9205
    ports:
      - 9100:443

  api-gateway-service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443
      - GlobalConfiguration__BaseUrl=http://api-gateway-service
      - Authentication__JwtBearer__Authority=http://api-auth-service/auth
      - Authentication__JwtBearer__ValidIssuer=https://localhost:9100/auth
      - Authentication__JwtBearer__RequireHttpsMetadata=false
      - Swagger__Security__Flow__AuthorityUrl=https://localhost:9100/auth
      - Routes__0__DownstreamScheme=http
      - Routes__0__DownstreamHostAndPorts__0__Host=api-identity-service
      - Routes__0__DownstreamHostAndPorts__0__Port=80
      - Routes__1__DownstreamScheme=http
      - Routes__1__DownstreamHostAndPorts__0__Host=api-movie-service
      - Routes__1__DownstreamHostAndPorts__0__Port=80
      - Routes__2__DownstreamScheme=http
      - Routes__2__DownstreamHostAndPorts__0__Host=api-payment-service
      - Routes__2__DownstreamHostAndPorts__0__Port=80
      - Routes__3__DownstreamScheme=http
      - Routes__3__DownstreamHostAndPorts__0__Host=api-review-service
      - Routes__3__DownstreamHostAndPorts__0__Port=80
      - Routes__4__DownstreamScheme=http
      - Routes__4__DownstreamHostAndPorts__0__Host=api-test-service
      - Routes__4__DownstreamHostAndPorts__0__Port=80
    ports:
      - 9200:443

  api-identity-service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - Authentication__JwtBearer__Authority=http://api-auth-service/auth
      - Authentication__JwtBearer__ValidIssuer=https://localhost:9100/auth
      - Authentication__JwtBearer__RequireHttpsMetadata=false
      - ConnectionStrings__IdentityServiceDbContext=Server=sqlserver,1433;Database=Microservice.DB.IdentityService;User Id=sa;Password=yourStrong(!)Password;TrustServerCertificate=True;
      - Swagger__Security__Flow__AuthorityUrl=https://localhost:9100/auth
    ports:
      - 9201:443

  api-identity-service-migrator:
    environment:
      - ConnectionStrings__IdentityServiceDbContext=Server=sqlserver,1433;Database=Microservice.DB.IdentityService;User Id=sa;Password=yourStrong(!)Password;TrustServerCertificate=True;
    depends_on:
      - sqlserver
      
  api-movie-service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - Authentication__JwtBearer__Authority=http://api-auth-service/auth
      - Authentication__JwtBearer__ValidIssuer=https://localhost:9100/auth
      - Authentication__JwtBearer__RequireHttpsMetadata=false
      - ConnectionStrings__MovieServiceDbContext=Server=sqlserver,1433;Database=Microservice.DB.MovieService;User Id=sa;Password=yourStrong(!)Password;TrustServerCertificate=True;
      - Swagger__Security__Flow__AuthorityUrl=https://localhost:9100/auth
    ports:
      - 9202:443

  api-movie-service-migrator:
    environment:
      - ConnectionStrings__MovieServiceDbContext=Server=sqlserver,1433;Database=Microservice.DB.MovieService;User Id=sa;Password=yourStrong(!)Password;TrustServerCertificate=True;
    depends_on:
      - sqlserver
      
  api-payment-service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - Authentication__JwtBearer__Authority=http://api-auth-service/auth
      - Authentication__JwtBearer__ValidIssuer=https://localhost:9100/auth
      - Authentication__JwtBearer__RequireHttpsMetadata=false
      - ConnectionStrings__PaymentServiceDbContext=Server=sqlserver,1433;Database=Microservice.DB.PaymentService;User Id=sa;Password=yourStrong(!)Password;TrustServerCertificate=True;
      - Swagger__Security__Flow__AuthorityUrl=https://localhost:9100/auth
    ports:
      - 9203:443

  api-payment-service-migrator:
    environment:
      - ConnectionStrings__PaymentServiceDbContext=Server=sqlserver,1433;Database=Microservice.DB.PaymentService;User Id=sa;Password=yourStrong(!)Password;TrustServerCertificate=True;
    depends_on:
      - sqlserver
      
  api-review-service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - Authentication__JwtBearer__Authority=http://api-auth-service/auth
      - Authentication__JwtBearer__ValidIssuer=https://localhost:9100/auth
      - Authentication__JwtBearer__RequireHttpsMetadata=false
      - ConnectionStrings__ReviewServiceDbContext=Server=sqlserver,1433;Database=Microservice.DB.ReviewService;User Id=sa;Password=yourStrong(!)Password;TrustServerCertificate=True;
      - Swagger__Security__Flow__AuthorityUrl=https://localhost:9100/auth
    ports:
      - 9204:443

  api-review-service-migrator:
    environment:
      - ConnectionStrings__ReviewServiceDbContext=Server=sqlserver,1433;Database=Microservice.DB.ReviewService;User Id=sa;Password=yourStrong(!)Password;TrustServerCertificate=True;
    depends_on:
      - sqlserver
      
  api-test-service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - Authentication__JwtBearer__Authority=http://api-auth-service/auth
      - Authentication__JwtBearer__ValidIssuer=https://localhost:9100/auth
      - Authentication__JwtBearer__RequireHttpsMetadata=false
      - ConnectionStrings__TestServiceDbContext=Server=sqlserver,1433;Database=Microservice.DB.TestService;User Id=sa;Password=yourStrong(!)Password;TrustServerCertificate=True;
      - RabbitMq__Host=rabbitmq
      - Swagger__Security__Flow__AuthorityUrl=https://localhost:9100/auth
    ports:
      - 9205:443

  api-test-service-migrator:
    environment:
      - ConnectionStrings__TestServiceDbContext=Server=sqlserver,1433;Database=Microservice.DB.TestService;User Id=sa;Password=yourStrong(!)Password;TrustServerCertificate=True;
    depends_on:
      - sqlserver