version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server
    environment:
      - MSSQL_SA_PASSWORD=yourStrong(!)Password
      - MSSQL_PID=Express
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    volumes:
      - dbdata:/var/opt/mssql  

  redis:
    image: "redis"

  rabbitmq:
    image: "rabbitmq:3-management-alpine"
    
volumes:
  dbdata: