version: '3.4'

services:
  gateway:
    image: ${DOCKER_REGISTRY-}gateway:${TAG:-latest}
    build:
      context: ../..
      dockerfile: applications/Microservice.Gateway/Dockerfile
    depends_on:
      - identity-server
      - identity-service
      - movie-service
      - payment-service
      - review-service
      - test-service

  identity-server:
    image: ${DOCKER_REGISTRY-}identity-server:${TAG:-latest}
    build:
      context: ../..
      dockerfile: applications/Microservice.IdentityServer/Dockerfile

  identity-service:
    image: ${DOCKER_REGISTRY-}identity-service:${TAG:-latest}
    build:
      context: ../..
      dockerfile: microservices/identity/Microservice.IdentityService.Api/Dockerfile
    depends_on:
      - identity-server

  movie-service:
    image: ${DOCKER_REGISTRY-}movie-service:${TAG:-latest}
    build:
      context: ../..
      dockerfile: microservices/movie/Microservice.MovieService.Api/Dockerfile
    depends_on:
      - identity-server

  payment-service:
    image: ${DOCKER_REGISTRY-}payment-service:${TAG:-latest}
    build:
      context: ../..
      dockerfile: microservices/payment/Microservice.PaymentService.Api/Dockerfile
    depends_on:
      - identity-server

  review-service:
    image: ${DOCKER_REGISTRY-}review-service:${TAG:-latest}
    build:
      context: ../..
      dockerfile: microservices/review/Microservice.ReviewService.Api/Dockerfile
    depends_on:
      - identity-server

  test-service:
    image: ${DOCKER_REGISTRY-}test-service:${TAG:-latest}
    build:
      context: ../..
      dockerfile: microservices/test/Microservice.TestService.Api/Dockerfile
    depends_on:
      - identity-server
