apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-test-service
spec:
  selector:
    matchLabels:
      app: api-test-service
  replicas: 1
  template:
    metadata:
      labels:
        app: api-test-service
    spec:
      containers:
        - name: api-test-service
          image: "api-test-service"
          imagePullPolicy: IfNotPresent
          env:
          - name: ASPNETCORE_ENVIRONMENT
            value: Production
          - name: ASPNETCORE_URLS
            value: http://0.0.0.0:80
          ports:
            - name: http
              containerPort: 80
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: api-test-service-autoscaler
spec:
  minReplicas: 1
  maxReplicas: 20
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-test-service
  targetCPUUtilizationPercentage: 50
---
apiVersion: v1
kind: Service
metadata:
  name: api-test-service
spec:
  selector:
    app: api-test-service
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: http