apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-identity-service
spec:
  selector:
    matchLabels:
      app: api-identity-service
  replicas: 1
  template:
    metadata:
      labels:
        app: api-identity-service
    spec:
      containers:
        - name: api-identity-service
          image: "api-identity-service"
          imagePullPolicy: IfNotPresent
          env:
          - name: ASPNETCORE_ENVIRONMENT
            value: Production
          - name: ASPNETCORE_URLS
            value: http://+:80
          - name: Authentication__JwtBearer__Authority
            value: http://api-auth-service/auth
          - name: Authentication__JwtBearer__ValidIssuer
            value: https://localhost/auth
          - name: Authentication__JwtBearer__RequireHttpsMetadata
            value: "false"
          - name: ConnectionStrings__IdentityServiceDbContext
            value: Server=sqlserver,1433;Database=Microservice.DB.IdentityService;User Id=sa;Password=yourStrong(!)Password;TrustServerCertificate=True;
          - name: Swagger__Security__Flow__AuthorityUrl
            value: https://localhost/auth
          ports:
            - name: http
              containerPort: 80
---
apiVersion: batch/v1
kind: Job
metadata:
  name: api-identity-service-migrator
spec:
  template:
    spec:
      containers:
        - name: api-identity-service-migrator
          image: "api-identity-service-migrator"
          imagePullPolicy: IfNotPresent
          env:
          - name: APP_ENVIRONMENT
            value: Production
          - name: ConnectionStrings__IdentityServiceDbContext
            value: Server=sqlserver,1433;Database=Microservice.DB.IdentityService;User Id=sa;Password=yourStrong(!)Password;TrustServerCertificate=True;
      restartPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: api-identity-service
spec:
  selector:
    app: api-identity-service
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: http