apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-service
spec:
  selector:
    matchLabels:
      app: api-gateway-service
  replicas: 1
  template:
    metadata:
      labels:
        app: api-gateway-service
    spec:
      containers:
        - name: api-gateway-service
          image: "api-gateway-service"
          imagePullPolicy: IfNotPresent
          env:
          - name: ASPNETCORE_ENVIRONMENT
            value: Production
          - name: ASPNETCORE_URLS
            value: http://0.0.0.0:80
          - name: GlobalConfiguration__BaseUrl
            value: http://gateway
          - name: Routes__0__DownstreamHostAndPorts__0__Host
            value: identity-service
          - name: Routes__0__DownstreamHostAndPorts__0__Port
            value: "80"
          - name: Routes__1__DownstreamHostAndPorts__0__Host
            value: movie-service
          - name: Routes__1__DownstreamHostAndPorts__0__Port
            value: "80"
          - name: Routes__2__DownstreamHostAndPorts__0__Host
            value: payment-service
          - name: Routes__2__DownstreamHostAndPorts__0__Port
            value: "80"
          - name: Routes__3__DownstreamHostAndPorts__0__Host
            value: review-service
          - name: Routes__3__DownstreamHostAndPorts__0__Port
            value: "80"
          - name: Routes__4__DownstreamHostAndPorts__0__Host
            value: test-service
          - name: Routes__4__DownstreamHostAndPorts__0__Port
            value: "80"
          ports:
            - name: http
              containerPort: 80
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: api-gateway-service-autoscaler
spec:
  minReplicas: 1
  maxReplicas: 20
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-gateway-service
  targetCPUUtilizationPercentage: 50
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
spec:
  selector:
    app: api-gateway-service
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: http