apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-test-service
spec:
  selector:
    matchLabels:
      app: api-test-service
  replicas: 1
  template:
    metadata:
      labels:
        app: api-test-service
    spec:
      containers:
        - name: api-test-service
          image: "api-test-service"
          imagePullPolicy: IfNotPresent
          env:
          - name: ASPNETCORE_ENVIRONMENT
            value: Production
          - name: ASPNETCORE_URLS
            value: http://+:80
          - name: Authentication__JwtBearer__Authority
            value: http://api-auth-service/auth
          - name: Authentication__JwtBearer__ValidIssuer
            value: https://localhost/auth
          - name: Authentication__JwtBearer__RequireHttpsMetadata
            value: "false"
          - name: ConnectionStrings__TestServiceDbContext
            value: Server=sqlserver,1433;Database=Microservice.DB.TestService;User Id=sa;Password=yourStrong(!)Password;TrustServerCertificate=True;
          - name: RabbitMq__Host
            value: rabbitmq
          - name: Swagger__Security__Flow__AuthorityUrl
            value: https://localhost/auth
          ports:
            - name: http
              containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: migrator-test-service
spec:
  selector:
    matchLabels:
      app: migrator-test-service
  template:
    metadata:
      labels:
        app: migrator-test-service
    spec:
      containers:
        - name: migrator-test-service
          image: "migrator-test-service"
          imagePullPolicy: IfNotPresent
          env:
          - name: APP_ENVIRONMENT
            value: Production
          - name: ConnectionStrings__TestServiceDbContext
            value: Server=sqlserver,1433;Database=Microservice.DB.TestService;User Id=sa;Password=yourStrong(!)Password;TrustServerCertificate=True;
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: api-test-service-autoscaler
spec:
  minReplicas: 1
  maxReplicas: 20
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-test-service
  targetCPUUtilizationPercentage: 50
---
apiVersion: v1
kind: Service
metadata:
  name: api-test-service
spec:
  selector:
    app: api-test-service
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: http