apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-auth-service
spec:
  selector:
    matchLabels:
      app: api-auth-service
  replicas: 1
  template:
    metadata:
      labels:
        app: api-auth-service
    spec:
      containers:
        - name: api-auth-service
          image: "api-auth-service"
          imagePullPolicy: IfNotPresent
          env:
          - name: ASPNETCORE_ENVIRONMENT
            value: Production
          - name: ASPNETCORE_URLS
            value: http://+:80
          - name: ConnectionStrings__IdentityServiceDbContext
            value: Server=sqlserver,1433;Database=Microservice.DB.IdentityService;User Id=sa;Password=yourStrong(!)Password;TrustServerCertificate=True;
          - name: IdentityServer__IssuerUri
            value: https://localhost/auth
          - name: IdentityServer__Clients__0__RedirectUris__0
            value: https://localhost/api/oauth2-redirect.html
          - name: IdentityServer__Clients__0__AllowedCorsOrigins__0
            value: https://localhost
          ports:
            - name: http
              containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: api-auth-service
spec:
  selector:
    app: api-auth-service
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: http