apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-server
spec:
  selector:
    matchLabels:
      app: identity-server
  replicas: 1
  template:
    metadata:
      labels:
        app: identity-server
    spec:
      containers:
        - name: identity-server
          image: "identity-server"
          imagePullPolicy: IfNotPresent
          env:
          - name: ASPNETCORE_ENVIRONMENT
            value: Production
          - name: ASPNETCORE_URLS
            value: http://0.0.0.0:80
          ports:
            - name: http
              containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: identity-server
spec:
  selector:
    app: identity-server
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: http