version: '3.4'

services:
  angular-ui:
    ports:
      - 9001:80

  react-ui:
    ports:
      - 9002:80

  gateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - GlobalConfiguration__BaseUrl=http://gateway
      - Routes__0__DownstreamHostAndPorts__0__Host=identity-service
      - Routes__0__DownstreamHostAndPorts__0__Port=80
      - Routes__1__DownstreamHostAndPorts__0__Host=movie-service
      - Routes__1__DownstreamHostAndPorts__0__Port=80
      - Routes__2__DownstreamHostAndPorts__0__Host=payment-service
      - Routes__2__DownstreamHostAndPorts__0__Port=80
      - Routes__3__DownstreamHostAndPorts__0__Host=review-service
      - Routes__3__DownstreamHostAndPorts__0__Port=80
      - Routes__4__DownstreamHostAndPorts__0__Host=test-service
      - Routes__4__DownstreamHostAndPorts__0__Port=80
    ports:
      - 9100:80

  identity-server:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 9111:80
      
  identity-service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 9201:80
      
  movie-service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 9202:80
      
  payment-service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 9203:80
      
  review-service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 9204:80
      
  test-service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 9205:80