version: '3.4'

services:
  angular-ui:
    ports:
      - 7000:80

  gateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - GlobalConfiguration__BaseUrl=http://gateway
      - Routes__0__DownstreamHostAndPorts__0__Host=identity-service
      - Routes__0__DownstreamHostAndPorts__0__Port=80
      - Routes__1__DownstreamHostAndPorts__0__Host=movie-service
      - Routes__1__DownstreamHostAndPorts__0__Port=80
      - Routes__2__DownstreamHostAndPorts__0__Host=payment-service
      - Routes__2__DownstreamHostAndPorts__0__Port=80
      - Routes__3__DownstreamHostAndPorts__0__Host=review-service
      - Routes__3__DownstreamHostAndPorts__0__Port=80
      - Routes__4__DownstreamHostAndPorts__0__Host=test-service
      - Routes__4__DownstreamHostAndPorts__0__Port=80
    ports:
      - 7100:80
      
  identity-service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 7101:80
      
  movie-service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 7102:80
      
  payment-service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 7103:80
      
  review-service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 7104:80
      
  test-service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 7105:80