version: '3.8'

services:
  angular-ui:
    container_name: "Microservice.AngularUI"
    image: ${DOCKER_REGISTRY-}angular-ui:${TAG:-latest}
    build:
      context: ../..
      dockerfile: applications/Microservice.AngularUI/docker/Dockerfile
    depends_on:
      gateway:
        condition: service_started

  react-ui:
    container_name: "Microservice.ReactUI"
    image: ${DOCKER_REGISTRY-}react-ui:${TAG:-latest}
    build:
      context: ../..
      dockerfile: applications/Microservice.ReactUI/docker/Dockerfile
    depends_on:
      gateway:
        condition: service_started