version: '3.4'

services:
  angular-ui:
    ports:
      - 9001:80

  react-ui:
    ports:
      - 9002:80

  gateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443
      - GlobalConfiguration__BaseUrl=http://gateway
      - Authentication__JwtBearer__Authority=http://identity-server
      - Authentication__JwtBearer__ValidIssuer=https://localhost:9111
      - Authentication__JwtBearer__RequireHttpsMetadata=false
      - Swagger__Security__Flow__AuthorityUrl=https://localhost:9111
      - Routes__0__DownstreamScheme=http
      - Routes__0__DownstreamHostAndPorts__0__Host=identity-service
      - Routes__0__DownstreamHostAndPorts__0__Port=80
      - Routes__1__DownstreamScheme=http
      - Routes__1__DownstreamHostAndPorts__0__Host=movie-service
      - Routes__1__DownstreamHostAndPorts__0__Port=80
      - Routes__2__DownstreamScheme=http
      - Routes__2__DownstreamHostAndPorts__0__Host=payment-service
      - Routes__2__DownstreamHostAndPorts__0__Port=80
      - Routes__3__DownstreamScheme=http
      - Routes__3__DownstreamHostAndPorts__0__Host=review-service
      - Routes__3__DownstreamHostAndPorts__0__Port=80
      - Routes__4__DownstreamScheme=http
      - Routes__4__DownstreamHostAndPorts__0__Host=test-service
      - Routes__4__DownstreamHostAndPorts__0__Port=80
    ports:
      - 9100:443

  identity-server:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - IdentityServer__Clients__0__RedirectUris__0=https://localhost:9100/oauth2-redirect.html
      - IdentityServer__Clients__0__RedirectUris__1=https://localhost:9201/oauth2-redirect.html
      - IdentityServer__Clients__0__RedirectUris__2=https://localhost:9202/oauth2-redirect.html
      - IdentityServer__Clients__0__RedirectUris__3=https://localhost:9203/oauth2-redirect.html
      - IdentityServer__Clients__0__RedirectUris__4=https://localhost:9204/oauth2-redirect.html
      - IdentityServer__Clients__0__RedirectUris__5=https://localhost:9205/oauth2-redirect.html
      - IdentityServer__Clients__0__AllowedCorsOrigins__0=https://localhost:9100
      - IdentityServer__Clients__0__AllowedCorsOrigins__1=https://localhost:9201
      - IdentityServer__Clients__0__AllowedCorsOrigins__2=https://localhost:9202
      - IdentityServer__Clients__0__AllowedCorsOrigins__3=https://localhost:9203
      - IdentityServer__Clients__0__AllowedCorsOrigins__4=https://localhost:9204
      - IdentityServer__Clients__0__AllowedCorsOrigins__5=https://localhost:9205
    ports:
      - 9111:443
      
  identity-service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - Authentication__JwtBearer__Authority=http://identity-server
      - Authentication__JwtBearer__ValidIssuer=https://localhost:9111
      - Authentication__JwtBearer__RequireHttpsMetadata=false
      - Swagger__Security__Flow__AuthorityUrl=https://localhost:9111
    ports:
      - 9201:443
      
  movie-service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - Authentication__JwtBearer__Authority=http://identity-server
      - Authentication__JwtBearer__ValidIssuer=https://localhost:9111
      - Authentication__JwtBearer__RequireHttpsMetadata=false
      - Swagger__Security__Flow__AuthorityUrl=https://localhost:9111
    ports:
      - 9202:443
      
  payment-service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - Authentication__JwtBearer__Authority=http://identity-server
      - Authentication__JwtBearer__ValidIssuer=https://localhost:9111
      - Authentication__JwtBearer__RequireHttpsMetadata=false
      - Swagger__Security__Flow__AuthorityUrl=https://localhost:9111
    ports:
      - 9203:443
      
  review-service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - Authentication__JwtBearer__Authority=http://identity-server
      - Authentication__JwtBearer__ValidIssuer=https://localhost:9111
      - Authentication__JwtBearer__RequireHttpsMetadata=false
      - Swagger__Security__Flow__AuthorityUrl=https://localhost:9111
    ports:
      - 9204:443
      
  test-service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - Authentication__JwtBearer__Authority=http://identity-server
      - Authentication__JwtBearer__ValidIssuer=https://localhost:9111
      - Authentication__JwtBearer__RequireHttpsMetadata=false
      - RabbitMq__Host=host.docker.internal
      - Swagger__Security__Flow__AuthorityUrl=https://localhost:9111
    ports:
      - 9205:443