version: '3.4'

services:
  angular-ui:
    image: ${DOCKER_REGISTRY-}angular-ui:${TAG:-latest}
    build:
      context: ../..
      dockerfile: applications/Microservice.AngularUI/docker/Dockerfile
    depends_on:
      - gateway

  gateway:
    image: ${DOCKER_REGISTRY-}gateway:${TAG:-latest}
    build:
      context: ../..
      dockerfile: gateways/Microservice.Gateway.Web/Dockerfile
    depends_on:
      - identity-service
      - movie-service
      - payment-service
      - review-service
      - test-service
      
  identity-service:
    image: ${DOCKER_REGISTRY-}identity-service:${TAG:-latest}
    build:
      context: ../..
      dockerfile: microservices/identity/Microservice.IdentityService.Web/Dockerfile
      
  movie-service:
    image: ${DOCKER_REGISTRY-}movie-service:${TAG:-latest}
    build:
      context: ../..
      dockerfile: microservices/movie/Microservice.MovieService.Web/Dockerfile
      
  payment-service:
    image: ${DOCKER_REGISTRY-}payment-service:${TAG:-latest}
    build:
      context: ../..
      dockerfile: microservices/payment/Microservice.PaymentService.Web/Dockerfile
      
  review-service:
    image: ${DOCKER_REGISTRY-}review-service:${TAG:-latest}
    build:
      context: ../..
      dockerfile: microservices/review/Microservice.ReviewService.Web/Dockerfile

  test-service:
    image: ${DOCKER_REGISTRY-}test-service:${TAG:-latest}
    build:
      context: ../..
      dockerfile: microservices/test/Microservice.TestService.Web/Dockerfile
